blogsite/blueprints/users/forms.py
# form module to be used
from flask_wtf import FlaskForm
# file uploading
from flask_wtf.file import FileField, FileAllowed
# form fields for the forms used
from wtforms import StringField, PasswordField, SubmitField, BooleanField
# validators for the forms used
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError

#variables called in forms imported from other files
from blogsite.models import User
from flask_login import current_user



############# USER FORMS #####################

# USER CREATE/NEW FORM
class RegistrationForm(FlaskForm):
	#pass validations as arguments
	username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
	email = StringField('Email', validators=[DataRequired(), Email()])
	password = PasswordField('Password', validators=[DataRequired()])
	confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
	submit = SubmitField('Sign Up')

	#custom validation for username
	def validate_username(self, username):
		user = User.query.filter_by(username=username.data).first()

		if user:
			raise ValidationError('Username already exist. Please choose a different username.')

	#custom validation for email
	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user:
			raise ValidationError('Email already exist. Please choose a different username.')

# USER UPDATE/EDIT FORM
class UpdateAccountForm(FlaskForm):
	#pass validations as arguments
	username = StringField('Username', 
		validators=[DataRequired(), Length(min=2, max=20)])
	email = StringField('Email', 
		validators=[DataRequired(), Email()])
	picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
	submit = SubmitField('Update')

	#custom validation for username
	def validate_username(self, username):
		if username.data != current_user.username:
			user = User.query.filter_by(username=username.data).first()

			if user:
				raise ValidationError('Username already exist. Please choose a different username.')

	#custom validation for email
	def validate_email(self, email):
		if email.data != current_user.email:
			user = User.query.filter_by(email=email.data).first()

			if user:
				raise ValidationError('Email already exist. Please choose a different username.')

blogsite/blueprints/users/routes.py
# render_tempalte adds templates to file # url_for links to routes  
# flash and redirect are for redirection after form submital and flash message
# abort renders 403 page
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint)
#imports the models
from blogsite.models import User
#import each created form classes from forms.py
from blogsite.blueprints.users.forms import RegistrationForm, UpdateAccountForm
# imports required variables from __init__
from blogsite import db, bcrypt
#imports required variables for logged in session
from flask_login import login_user, current_user, logout_user, login_required
#image uploader
from blogsite.blueprints.users.image_helper import upload_file_to_s3, allowed_profile_images, delete_file_from_s3
#secure naming
from werkzeug.utils import secure_filename
#minify
from htmlmin.minify import html_minify

users = Blueprint('users', __name__)
############# USER RESOURCES/ROUTES #####################

# USER CREATE/NEW
@users.route("/register", methods=['GET', 'POST'])
def register():
	#set form = imported RegistrationForm Class
	form = RegistrationForm()
	#form validation for form 
	if form.validate_on_submit():
		# created crypted password for user on database
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		#create user in database
		user = User(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash(f'Account created! You are no able to login!', 'success')
		return redirect(url_for('main.home'))
	return render_template('users/new.html', title='Register', form=form)#call form as argument

# USER EDIT/UPDATE/ACCOUNT
@users.route("/users/<string:username>/edit", methods=['GET','POST'])
@login_required
def edit(username):
	user = User.query.filter_by(username=username).first_or_404()
	if user != current_user:
		abort(403)
	form = UpdateAccountForm()
	if form.validate_on_submit():
		# if form.picture.data:
		# 	file = form.picture.data
		# if file and allowed_profile_images(file.filename):
		# 	old_filename = user.image_file
		# 	delete_file_from_s3(old_filename)
		# 	file.filename = secure_filename(user.username + "-" + file.filename)
		# 	output = upload_file_to_s3(file)
		# 	current_user.picture_file = file.filename

		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Account Updated', 'success')
		return redirect(url_for('main.home'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	# image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
	render_html = render_template('users/edit.html', title='Account', user=current_user,form=form)
	return html_minify(rendered_html)

# USER PROFILE IMAGE ROUTE
@users.route("/users/<string:username>/image", methods=['POST'])
@login_required
def upload_profile_image(username):
	form = UpdateAccountForm()
	user = User.query.filter_by(username=username).first_or_404()

    # Prevent unauthorized user from changing data of another user
	if not user.id == current_user.id:
		return render_template('users/edit.html', validation_errors=['Unauthorized!'], form=form, user=user)
	# Check if image in file for upload
	if "image_file" not in request.files:
		flash("No profile image")
		rendered_html = render_template('users/edit.html', validation_errors=[], form=form, user=user)
		return html_minify(rendered_html)
	file = request.files["image_file"]

	# if no filename ask for new image
	if file.filename == "":
		flash("Please select a file")
		rendered_html = render_template('edit.html', form=form)
		return html_minify(rendered_html)

	# check if file extension is acceptable
	if file and allowed_profile_images(file.filename):
		# if there is a previous file delete the file
		old_filename = user.image_file
		delete_file_from_s3(old_filename)

		# create a custom name for file
		file.filename = secure_filename(user.username + "-" + file.filename)
		# upload the file
		output = upload_file_to_s3(file)
		# set the user image file equal the bucket url
		user.image_file = output
	
		db.session.commit()
		flash("Profile Picture Updated!")

		#redirect the user create the post action
		return redirect(url_for('main.home'))

	else:
		return redirect("/")

blogsite/templates/users/edit.html
<div class="row">
  <div class="col">
    <div class="media">
      <img class="rounded-circle account-img" src="{{image_file}}">
      <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>

      </div>
    </div>
    <!-- enctype is for uploads -->
    <form method="POST" action="" enctype="multipart/form-data">
      <!-- adds crf token protection -->
      {{ form.hidden_tag() }} 
      <fieldset class='form-group'>
        <legend class="border_bottom mb-4">Account Info</legend>
        <div class="form-group">
            {{ form.username.label(class="form-control-label") }}

            {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info")}}
      </div>
    </form>
  </div>
</div>

<div class="row">
  <div class="col-3">

    {% if user.image_file %}
    {% set download = user.image_file.replace("http","https") %}
      <a href="{{user.image_file}}" download>Certificate </a>
    {% endif %}
  </div>

<div class="row">
  <div class="col">
    <h2>Change Your Profile Picture</h2>
  </div>
</div>

<div class="row">
  <div class="col-3">
    {% if user.image_file %}
      <img src="{{user.image_file}}" class="profile-picture-edit rounded float-left" alt="{{user.username}}-profile-picture"/>
    {% else %}
      <img src="https://s3.amazonaws.com/next-curriculum-instagram/profile-placeholder.jpg" class="profile-picture-edit rounded float-left" alt="{{user.username}}-profile-picture"/>
    {% endif %}
  </div>
  <div class="col-9">
    <form action={{url_for("users.upload_profile_image", username=user.username)}} method="POST" enctype="multipart/form-data">
      <input type="file" name="image_file">
      <button class="btn btn-primary" type="submit">Upload</button>
    </form>
  </div>
</div>

blogsite/templates/users/new.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="content-section">
    	<form method="POST" action="">
    		<!-- adds crf token protection -->
    		{{ form.hidden_tag() }} 
    		<fieldset class='form-group'>
    			<legend class="border_bottom mb-4">Join Today</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}

                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.confirm_password.label(class="form-control-label") }}
                        {% if form.confirm_password.errors %}
                            {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.confirm_password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.confirm_password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
    			
    			</fieldset>
    		<div class="form-group">
    			{{ form.submit(class="btn modal-buttons")}}
    		</div>

    	</form>
    </div>
</div>
{% endblock content %}