blogsite/blueprints/main/routes.py
from flask import render_template, request, Blueprint, send_from_directory
from htmlmin.minify import html_minify
import os
#imports the models
# from blogsite.models import Post

main = Blueprint('main', __name__)


# APP INDEX/HOMEPAGE
@main.route("/")
#set multiple routes to same page
@main.route("/homepage")
def home():
	# return the template for route page
	rendered_html = render_template('home.html')
	return html_minify(rendered_html)


# APP ROBOTS.TXT
@main.route("/robots.txt")
def robots():
    return send_from_directory('static', 'robots.txt')

# APP SITEMAP.XML
@main.route("/sitemap.xml")
def sitemap():
    return send_from_directory('static', 'sitemap.xml')

blogsite/blueprints/users/routes.py
# render_tempalte adds templates to file # url_for links to routes  
# flash and redirect are for redirection after form submital and flash message
# abort renders 403 page
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint)
#imports the models
from blogsite.models import User
#import each created form classes from forms.py
from blogsite.blueprints.users.forms import RegistrationForm, UpdateAccountForm
# imports required variables from __init__
from blogsite import db, bcrypt
#imports required variables for logged in session
from flask_login import login_user, current_user, logout_user, login_required
#image uploader
from blogsite.blueprints.users.image_helper import upload_file_to_s3, allowed_profile_images, delete_file_from_s3
#secure naming
from werkzeug.utils import secure_filename
#minify
from htmlmin.minify import html_minify

users = Blueprint('users', __name__)
############# USER RESOURCES/ROUTES #####################

# USER CREATE/NEW
@users.route("/register", methods=['GET', 'POST'])
def register():
	#set form = imported RegistrationForm Class
	form = RegistrationForm()
	#form validation for form 
	if form.validate_on_submit():
		# created crypted password for user on database
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		#create user in database
		user = User(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash(f'Account created! You are no able to login!', 'success')
		return redirect(url_for('main.home'))
	return render_template('users/new.html', title='Register', form=form)#call form as argument

# USER EDIT/UPDATE/ACCOUNT
@users.route("/users/<string:username>/edit", methods=['GET','POST'])
@login_required
def edit(username):
	user = User.query.filter_by(username=username).first_or_404()
	if user != current_user:
		abort(403)
	form = UpdateAccountForm()
	if form.validate_on_submit():
		# if form.picture.data:
		# 	file = form.picture.data
		# if file and allowed_profile_images(file.filename):
		# 	old_filename = user.image_file
		# 	delete_file_from_s3(old_filename)
		# 	file.filename = secure_filename(user.username + "-" + file.filename)
		# 	output = upload_file_to_s3(file)
		# 	current_user.picture_file = file.filename

		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Account Updated', 'success')
		return redirect(url_for('main.home'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	# image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
	render_html = render_template('users/edit.html', title='Account', user=current_user,form=form)
	return html_minify(rendered_html)

# USER PROFILE IMAGE ROUTE
@users.route("/users/<string:username>/image", methods=['POST'])
@login_required
def upload_profile_image(username):
	form = UpdateAccountForm()
	user = User.query.filter_by(username=username).first_or_404()

    # Prevent unauthorized user from changing data of another user
	if not user.id == current_user.id:
		return render_template('users/edit.html', validation_errors=['Unauthorized!'], form=form, user=user)
	# Check if image in file for upload
	if "image_file" not in request.files:
		flash("No profile image")
		rendered_html = render_template('users/edit.html', validation_errors=[], form=form, user=user)
		return html_minify(rendered_html)
	file = request.files["image_file"]

	# if no filename ask for new image
	if file.filename == "":
		flash("Please select a file")
		rendered_html = render_template('edit.html', form=form)
		return html_minify(rendered_html)

	# check if file extension is acceptable
	if file and allowed_profile_images(file.filename):
		# if there is a previous file delete the file
		old_filename = user.image_file
		delete_file_from_s3(old_filename)

		# create a custom name for file
		file.filename = secure_filename(user.username + "-" + file.filename)
		# upload the file
		output = upload_file_to_s3(file)
		# set the user image file equal the bucket url
		user.image_file = output
	
		db.session.commit()
		flash("Profile Picture Updated!")

		#redirect the user create the post action
		return redirect(url_for('main.home'))

	else:
		return redirect("/")

blogsite/templates/home.html
{% extends "layout.html" %}
{% block content %}
<!-- main image  -->
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" id="hero" src="https://s3-ap-southeast-1.amazonaws.com/cambomakeup/SreyNy.png" alt="First slide">
    </div>
  </div>
</div>


<!-- scroll down button -->
<div id="container-floating" class="fadeInRight">
	<img src="https://s3-ap-southeast-1.amazonaws.com/cambomakeup/9ccbffe2fecf0b817eff9d5147f4be33%2B(1).png" id="floating-button" data-toggle="tooltip" data-placement="left" data-original-title="Create">
	<p class="eng-link">Touch</p>
	<p class="khmer-link" style="padding-top:0px!important;margin-top: -10px!important;margin-left: 75px!important">ចុច</p>
</div>

</div>

<!-- seperator image -->
<div class="row" style='margin-right: 0;margin-left: 0;'>
	<div class="col-md-3">
	</div>
	<div class="col-md-9 img-fluid" style="background-image: url('https://s3-ap-southeast-1.amazonaws.com/cambomakeup/23577e7a7eb8829.png');background-repeat: no-repeat;background-size: 100% 100%;height: 35vh;margin-top: -50px">
	</div>
</div>

<!-- about the artist -->
<section id="about" class="pt-5 pb-5" style="background-color: #fffafa;">
	<div class="container">
		<h1 class="text-center" style="display: none;">  Cambo Makeup by SreyNy Cambodias Best Studio </h1>
		<div class='row shadow' id="aboutImage">
			<div class="col-md-6" style="text-align: center;">

				<img src="https://s3-ap-southeast-1.amazonaws.com/cambomakeup/IMG_5808.jpg" class="img-fluid shadow-cu rounded" id="aboutImage" style="height: 400px;" >
			</div>
			<div class="col-md-6 text-center align-items-center" id="aboutText">
				<h2 class="text-uppercase font-weight-bold" style="margin-top: 60px;">
					<span class="eng-link">Makeup Artist</span>
					<span class="khmer-link" >អ្នកផាត់មុខ</span>
				</h2>
					<p class="mt-4" id="bio" style="font-family: 'Lato', sans-serif;line-height: 1.7;font-size: 1.3rem;"><em>
					SreyNy is a Cambodian based Freelance Makeup Artist.
					</em></p>
				</h2>
			</div>
		</div>
	</div>
</section>
<!-- services  -->
<section class="pt-5 pb-5" id='services' style="background-color: #fffafa;">
	<div class="container">
		<div class="col-md-12 text-center mb-4">
			<h2 class="text-uppercase font-weight-bold" id="serviceH2"> 
			<span class="eng-link">SERVICES</span>
			<span class="khmer-link" >សេវាកម្ម​</span>
		</h2>
		</div>
		<div class="row">
			<div class="col-md-4 text-center"  id='serviceImage1'>
				<img src="{{url_for('static', filename='images/makeup.png')}}">
				<h4>
					<span class="eng-link">MAKEUP</span>
					<span class="khmer-link" >ផាត់មុខ</span>
				</h4>
				<p><em>For a wedding, photo shoot, a portrait, or just a night out, we will make you feel beautiful.</em></p>
			</div>
			<div class="col-md-4 text-center" id='serviceImage2'>
				<img src="{{url_for('static', filename='images/hair.png')}}">
				<h4>
					<span class="eng-link">HAIRSTYLING</span>
					<span class="khmer-link" >ស្ទីលម៉ូដសក់</span>
				</h4>
				<p><em>We can do anything from updos to long, flowing curls and everything in-between.</em></p>
			</div>
			<div class="col-md-4 text-center" id='serviceImage3'>
				<img src="{{url_for('static', filename='images/beauty.png')}}">
				<h4>
					<span class="eng-link">BEAUTY BAR</span>
					<span class="khmer-link">ធ្វើក្រចក កាត់សាច់ និងលាបថ្នាំក្រចក</span>

				</h4>
				<p><em>Our full service Beauty Bar has you covered. </em></p>
			</div>
		</div>
	</div>
</section>

<!-- instagram gallery -->
<section class="gallery-block compact-gallery pt-5 pb-5" style="background-color: #fffafa;">
    <div class="container">
        <div id='gallery'>
        	<div class="col-md-12">
            	<h2 class="text-uppercase text-center font-weight-bold"  id="galleryH2">
					<span class="eng-link">Gallery</span>
					<span class="khmer-link" >រូបថត</span>
				</h2>
			</div>
			<div class="text-center pt-2" id="galleryUl">
				<ul class="menu list-inline">
	                <li class="list-inline-item" id="viewStyle">
	                	<span class="eng-link">LATEST</span>
						<span class="khmer-link" >ថ្មីបំផុត</span>
	                </li>	 
	                <li class="list-inline-item" id="weddingStyle">
						<span class="eng-link">WEDDING</span>
						<span class="khmer-link" >ពិធីមង្គលការ ផាត់មុខ</span>	                 	
	                </li>
	                       
	                <li class="list-inline-item" id="eveningStyle">
	                	<span class="eng-link">EVENING</span>
						<span class="khmer-link" >ផាត់មុខចូលរួមកម្មវិធីផ្សេងៗ</span>
	                </li>
	                       
	                <li class="list-inline-item" id="khmerStyle">
	                	<a href="https://www.instagram.com/sreynymet/" target="_blank" style="text-decoration:none;color:inherit;">
	                 		<span class="eng-link" >VIEW MORE</span>
							<span class="khmer-link" >មើល​បន្ថែម​ទៀត</span>
						</a>
	                </li>
               
	            </ul>
	        </div>
	        <center><div class="loader"></div></center>
	        <div class="instagram_feed">
            	<div class="instagram-feed mt-4"></div>
            </div>
            
        </div>
    </div>
</section>
{% endblock content %}

blogsite/templates/layout.html
<!doctype html>
<html lang="en">
 	<head>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="keywords" content="cambodia makeup,cambodia makeup artist, phnom pehn, cambodia, best, wedding, bridal makeup, photo makeup, product, hair styling, stylist, hair, makeup, makeup artist, make-up, cambomakeup, cambodian makeup, khmer, khmer makeup">
	    <meta name="description" content="Cambo Makeup is a premier Makeup Studio in Phnom Pehn, Cambodia. Contact us for all your makeup needs.">
	    <meta property="og:image" content="https://s3-ap-southeast-1.amazonaws.com/cambomakeup/POTENTIAL+LOGO+(1).png" />
	    <meta property="og:locale" content="en_US">
	    <meta property="og:type" content="website">
	    <meta property="og:title" content="Best Makeup Artist in Cambodia | Cambo Makeup Studio by SreyNy">
	    <meta property="og:description" content="Cambo Makeup is a premier Makeup Studio in Phnom Pehn, Cambodia. Contact us for all your makeup needs.">
	    <meta property="og:url" content="http://cambomakeup.com">
	    <meta property="og:site_name" content="Cambo Makeup">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	    <link rel="canonical" href="http://cambomakeup.com">
	    <!-- End Required meta tags -->
	    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.png')}}">
	   	 <!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	    <!-- fontawesome CSS -->
	    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

	    <!-- Lightbox CSS -->
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" />

		<!-- Onscroll CSS -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css">

		<!-- Main App CSS -->
		{% assets "main_css" %}
		    <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
		{% endassets %}
		<!-- Title section -->
		{% if title%}
			<title>{{ title }}</title>
		{% else %}
			<title>Best Makeup Artist in Cambodia | Cambo Makeup Studio by SreyNy</title>
		{% endif%}
		<!-- End Title Section -->
	</head>
	<body>
		<header class="site-header">

			<!-- Navigation bar -->
			<nav class="navbar navbar-expand-lg navbar-light fixed-top navbar-inverse bg-inverse">
				<div class="container" id="navContain">
					<a href='/'><img class="navbar-brand mx-auto sticky-top mr-auto" id='logo' src="https://s3-ap-southeast-1.amazonaws.com/cambomakeup/POTENTIAL+LOGO+(1).png" ></a>
					<button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target=".navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse navbarToggle" id='dropDown'>
						<ul class="navbar-nav ml-auto" ">
							<li><i class="fas fa-phone fa-flip-horizontal"></i> +855 086 607 753</li>
							<!-- Dropdown Language Toggle -->
							<li class="nav-item lang" id="dropDownLang" style="display: none;">
								<img class="eng-link" src="https://image.flaticon.com/icons/svg/164/164928.svg" style="width:35px;height: 35px;">
								<img src="https://image.flaticon.com/icons/svg/168/168172.svg" class="khmer-link" style="width:35px;height: 35px;">
							</li>
							<!-- End Dropdown Language toggle -->

						    <!-- logout user link if logged in -->
						   	{% if current_user.is_authenticated %}
						   		<li class="nav-item nav-link">
						   			<a class="nav-item nav-link" href="{{ url_for('sessions.logout')}}">Logout</a>
						   		</li>
						   	{% else %}
						   	<!-- login link and register if not logged in -->
						   	<!-- <li class="nav-item nav-link"> -->
						    	<!-- <a class="nav-item nav-link" href="{{ url_for('sessions.login')}}">Login</a> -->
						    <!-- </li> -->
						    <!-- <li class="nav-item nav-link"> -->
						    	<!-- a href="{{url_for('users.register')}}">Register</a> -->
						    <!-- </li> -->
						    {% endif %}
						</ul>
						<ul class="navbar-nav ml-auto">
							<!-- Services Link -->
							<a href="{{url_for('main.home')+'#services'}}" id='servicesNav' style="text-decoration: none;" data-toggle="collapse" data-target=".navbar-collapse.show">
								<li class="nav-item nav-link eng-link text-uppercase" > Services</li>
						    	<li class="nav-item nav-link khmer-link" > សេវាកម្ម​</li>
							</a>
						    <!-- Wedding Info Link -->
						    <li class="nav-item nav-link eng-link text-uppercase" > Wedding</li>
						    <li class="nav-item nav-link khmer-link" > ពិធីមង្គលការ</li>
						    <!-- Pricing/Booking Link + Pop up Modal-->
						    <div data-toggle="modal" data-target="#myModal" id="pricingLink">
						    	<li class="nav-item nav-link eng-link text-uppercase"  data-toggle="collapse" data-target=".navbar-collapse.show" >Pricing</li>
						    	<li class="nav-item nav-link khmer-link"  data-toggle="collapse" data-target=".navbar-collapse.show">តម្លៃ</li>
							</div>
						    <!-- Gallery Link-->
						    <a href="{{url_for('main.home')+'#gallery'}}" id='galleryNav' style="text-decoration: none;" data-toggle="collapse" data-target=".navbar-collapse.show">
						    	<li class="nav-item nav-link eng-link text-uppercase"> Gallery</li>
						    	<li class="nav-item nav-link khmer-link" > រូបថត</li>
							</a>
						</ul>
						
						<ul class="navbar-nav ml-auto" id="socialNav">
							<!-- Social Contact buttons -->
							<li class="nav-item"><a href="https://www.facebook.com/meth.sreyny" class="nav-link" target="_blank"><i class="fab fa-facebook-f "></i></a></li>
							<li class="nav-item"><a href="https://www.instagram.com/sreynymet/" class="nav-link" target="_blank"><i class="fab fa-instagram "></i></a></li>
							<li class="nav-item"><a href="https://www.youtube.com/channel/UC-pr1rHvP72VbwIuNwhwuHg" class="nav-link" target="_blank"><i class="fab fa-youtube "></i></a></li>
							<li class="nav-item"><a href="https://www.messenger.com/t/meth.sreyny/" target="_blank" class="nav-link"><i class="fab fa-facebook-messenger "></i></a></li>
							<!-- End Social Contact buttons -->

							<!-- Language Toggle -->
							<li class="nav-item lang">
								<img class="eng-link" src="https://image.flaticon.com/icons/svg/164/164928.svg" style="width:35px;height: 35px;">
								<img src="https://image.flaticon.com/icons/svg/168/168172.svg" class="khmer-link" style="width:35px;height: 35px;">
							</li>
							<!-- End Language Toggle -->
						</ul>
						

						<!-- Dropdown Social Contact button -->
						<ul class="navbar-nav" id="socialDN">
							<li class="nav-item mt-2">
							<a href="https://www.facebook.com/meth.sreyny" target="_blank" class="pr-4"><i class="fab fa-2x fa-facebook-f "></i></a>
							<a href="https://www.instagram.com/sreynymet/" target="_blank" class="pr-4"><i class="fab fa-2x fa-instagram "></i></a>
							<a href="https://www.youtube.com/channel/UC-pr1rHvP72VbwIuNwhwuHg" target="_blank" class="pr-4"><i class="fab fa-2x fa-youtube "></i></a>
							<a href="https://www.messenger.com/t/meth.sreyny/" target="_blank" class="pr-4"><i class="fab fa-2x fa-facebook-messenger "></i></a>
							</li>
						</ul>
						<!-- End Dropdown Social Contact buttons -->
				  	</div>
				</div>
			</nav>
			<!-- End Navigation Bar -->
		</header>
		<!-- Flash Messages screen -->
		<main role="main" class="container mt-5">
		  	<div class="row">
			    <div class="col-md-8">
			    	<!-- allows flash messages to be seen -->
			    	{% with messages = get_flashed_messages(with_categories=true) %}
			    		{% if messages %}
			    			{% for category, message in messages %}
			    				<div class='alert alert-{{ category }}'>

			    					{{ message}}
			    					
			    				</div>
			    			{% endfor %}
			    		{% endif %}
			    	{% endwith %}
				</div>
		  	</div>			
		</main>
		<!-- End Flash Messages screen -->

		<!-- Side Booking Button -->
		<div id="sideButton" style="float:none; position: fixed; top: 25%; display: block; z-index: 1000" data-toggle="modal" data-target="#myModal" >
			<img border="none" src="https://s3-ap-southeast-1.amazonaws.com/cambomakeup/Photograpy%2BWorkshop%2B(1).png" alt="Book an appointment with Cambo Makeup" />
		</div>
		<!-- End Side Booking Button -->

		<!-- sets the yield to bring in other templates from folder like a wrapper around your html code -->
		{% block content %}{% endblock %}

		<!--Modal: booking page -->
		<div class="modal fade" id="myModal" tabindex="-1">
		  	<div class="modal-dialog modal-dialog-centered">
			    <!--Content-->
			    <div class="modal-content" style="height: 90%;overflow: scroll; -webkit-overflow-scrolling: touch!important; width: 100%;height: 100%;">

					<!--Body-->
					<div class="modal-body mb-0 p-0">
						<div >
							<center><div class="pricing-loader"></div></center>
							<iframe id="bookingFrame" style="border: 0px;width: 100%; height: 500px;" src="" scrollable="no" width="100%" height="100%"> </iframe>
						</div>	  
					</div>
					<!-- footer -->
			    	<div class="modal-footer">
			    	 	<button type="button" class="btn btn-sm modal-buttons pull-left" id="resetBooking">Reset</button>
						<button type="button" class="btn btn-sm modal-buttons" data-dismiss="modal">Close</button>
					</div>
			    </div>
			    <!-- End Content-->
		  </div>
		  <!-- End Modal -->
		</div>

		<!-- Footer -->
		<footer class="footer" id="footerScroll">
		    <div class="container">
		    	<div class='row'>
			        <div class="col-md-6 text-center">
			            <ul class="list-inline">		
			                <li class="list-inline-item">
			                    <a href="https://www.facebook.com/meth.sreyny" target="_blank" class="pr-4"><i class="fab fa-2x fa-facebook-f "></i></a>
			                </li>
			               
			                <li class="list-inline-item">
			                    <a href="https://www.instagram.com/sreynymet/" target="_blank" class="pr-4"><i class="fab fa-2x fa-instagram "></i></a>
			                </li>
			               
			                <li class="list-inline-item">
			                    <a href="https://www.youtube.com/channel/UC-pr1rHvP72VbwIuNwhwuHg" target="_blank" class="pr-4"><i class="fab fa-2x fa-youtube "></i></a>
			                </li>
			               
			                <li class="list-inline-item">
			                    <a href="https://www.messenger.com/t/meth.sreyny/" target="_blank" class="pr-4"><i class="fab fa-2x fa-facebook-messenger "></i></a>
			                </li>
			                
			            </ul>
			        </div>
			             
			        <div class="col-md-6 text-center">   
			            <ul class="menu list-inline">
			                <li class="list-inline-item">
			                    <a href="#">Home</a>
			                </li>
			                       
			                <li class="list-inline-item">
			                   <a href="#about">About</a>
			                </li>
			                       
			                <li class="list-inline-item">
			                    <a href="#services">Services</a>
			                </li>
			                       
			                <li class="list-inline-item">
			                    <a href="#gallery">Gallery</a>
			                </li>
			                       
			                <li class="list-inline-item">
			                   <a href="https://www.messenger.com/t/meth.sreyny/">Contact</a>
			                </li>
			            </ul>
			        </div>
		    	</div>
		    </div>
	        <div class="container">
    			<div id='copyright'>
	            	<p class="text-uppercase text-center font-weight-bold" style="color:#b1aca1;margin:15px 0px;font-family: 'Source Sans Pro', sans-serif;">
						<span>Copyright © 2019 All rights reserved</span>
					</p>
	            
	        	</div>
			</div>
	    </footer>
	    <!-- End Footer -->

	    <!-- <section class="gallery-block compact-gallery"> -->

		<!-- </section> -->

		<!-- BOOTSTRAP REQUIRED jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

		<!-- onscroll js -->
		<script src="//ajax.aspnetcdn.com/ajax/modernizr/modernizr-2.7.2.js"></script>

		<!-- lightbox cdn -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.js"></script>

		<!-- main app js -->
		{% assets "main_js" %}
		    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
		{% endassets %}
	</body>
</html>

blogsite/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
	<div class="content-section">
		<form method="POST" action="">
			<!-- adds crf token protection -->
			{{ form.hidden_tag() }} 
			<fieldset class='form-group'>
				<legend class="border_bottom mb-4">Login</legend>

				<div class="form-group">
	                {{ form.email.label(class="form-control-label") }}
	                {% if form.email.errors %}
	                    {{ form.email(class="form-control form-control-lg is-invalid") }}
	                    <div class="invalid-feedback">
	                        {% for error in form.email.errors %}
	                            <span>{{ error }}</span>
	                        {% endfor %}
	                    </div>
	                {% else %}
	                    {{ form.email(class="form-control form-control-lg") }}
	                {% endif %}
				</div>

				<div class="form-group">
	                {{ form.password.label(class="form-control-label") }}
	                {% if form.password.errors %}
	                    {{ form.password(class="form-control form-control-lg is-invalid") }}
	                    <div class="invalid-feedback">
	                        {% for error in form.password.errors %}
	                            <span>{{ error }}</span>
	                        {% endfor %}
	                    </div>
	                {% else %}
	                    {{ form.password(class="form-control form-control-lg") }}
	                {% endif %}
				</div>

				<div class="form-check">
					{{ form.remember(class="form-check-input")}}
					{{ form.remember.label(class="form-check-label")}}
				</div>
				
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn modal-buttons")}}
			</div>
			<small class="text-muted ml-2">
				<a href="{{url_for('passwords.reset_request')}}">Forgot Password?</a>
			</small>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			New User? <a class="ml-2" href="{{url_for('users.register')}}"> Sign Up </a>
		</small>
	</div>	
</div>
{% endblock content %}

blogsite/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
	<form method="POST" action="">
		<!-- adds crf token protection -->
		{{ form.hidden_tag() }} 
		<fieldset class='form-group'>
			<legend class="border_bottom mb-4">Reset Password</legend>

			<div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
			</div>
			
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info")}}
		</div>

	</form>
</div>


{% endblock content %}